use std::{
    env, fs,
    path::{Path, PathBuf},
};

fn main() {
    if cfg!(feature = "docs-only") {
        return;
    }

    // Tell Cargo to rerun if anything in the SDK changes
    println!("cargo:rerun-if-changed=OrbbecSDK");
    println!("cargo:rerun-if-changed=build.rs");

    let out = PathBuf::from(env::var("OUT_DIR").unwrap());
    let src = PathBuf::from("OrbbecSDK");
    let work_src = out.join("orbbec_src");
    let stamp = out.join("orbbec_src.stamp");

    let current_stamp = dir_fingerprint(&src).unwrap();

    let needs_refresh = match fs::read_to_string(&stamp) {
        Ok(old) => old != current_stamp,
        Err(_) => true,
    };

    if needs_refresh {
        if work_src.exists() {
            fs::remove_dir_all(&work_src).unwrap();
        }
        copy_dir_all(&src, &work_src).unwrap();
        fs::write(&stamp, &current_stamp).unwrap();
    }

    // Configure and build the C++ library using CMake
    let mut dst = cmake::Config::new(work_src.clone());
    dst.define("CMAKE_POLICY_VERSION_MINIMUM", "3.10");
    dst.define("OB_BUILD_EXAMPLES", "OFF");
    dst.define("OB_BUILD_TESTS", "OFF");
    dst.define("OB_BUILD_TOOLS", "OFF");
    dst.define("OB_BUILD_DOCS", "OFF");

    // cmake-rs has some issues setting the correct flags on Windows
    #[cfg(target_os = "windows")]
    dst.static_crt(true)
        .cflag("/DWIN32 /D_WINDOWS -w")
        .cxxflag("/DWIN32 /D_WINDOWS -w /EHsc");

    // Disable warnings
    #[cfg(not(target_os = "windows"))]
    dst.cflag("-w").cxxflag("-w");

    let dst = dst.build();

    // Binary directory differs between Windows and Unix
    #[cfg(target_os = "windows")]
    let bin_folder = "bin";

    #[cfg(not(target_os = "windows"))]
    let bin_folder = "lib";

    let bin_dir = dst.join(bin_folder);
    let target_dir = dst.join("../../../");

    // Copy extension directory to target_dir
    let extensions_dir = bin_dir.join("extensions");
    let dest_extensions_dir = target_dir.join("extensions");
    if !dest_extensions_dir.exists() {
        std::fs::create_dir_all(&dest_extensions_dir)
            .expect("Failed to create extensions directory");
    }

    // Go through each folder in extensions_dir and copy to dest_extensions_dir
    for entry in std::fs::read_dir(&extensions_dir).unwrap() {
        let entry = entry.unwrap();
        let path = entry.path();
        if path.is_dir() {
            let folder_name = path.file_name().unwrap();
            let dest_folder = dest_extensions_dir.join(folder_name);
            if !dest_folder.exists() {
                std::fs::create_dir_all(&dest_folder)
                    .expect("Failed to create extension subdirectory");
            }

            for file_entry in std::fs::read_dir(&path).unwrap() {
                let file_entry = file_entry.unwrap();
                let file_path = file_entry.path();
                if let Some(ext) = file_path.extension()
                    && (ext == "dll" || ext == "so" || ext == "dylib")
                {
                    let file_name = file_path.file_name().unwrap();
                    let dest_file = dest_folder.join(file_name);
                    std::fs::copy(&file_path, &dest_file)
                        .expect("Failed to copy extension library file");
                }
            }
        }
    }

    // Copy libraries to target directory
    for entry in std::fs::read_dir(&bin_dir).unwrap() {
        let entry = entry.unwrap();
        let path = entry.path();
        if let Some(ext) = path.extension()
            && (ext == "dll" || ext == "so" || ext == "dylib")
        {
            let file_name = path.file_name().unwrap();
            let dest = target_dir.join(file_name);
            std::fs::copy(&path, &dest).expect("Failed to copy library file");
        }
    }

    // Tell cargo to tell rustc to link the OrbbecSDK library
    println!(
        "cargo:rustc-link-search=native={}",
        dst.join("lib").display()
    );
    println!("cargo:rustc-link-lib=OrbbecSDK");

    // Generate bindings using bindgen
    #[cfg(feature = "buildtime-bindgen")]
    {
        // Export.h is generated by CMake during configure and is required by
        // the public headers. Copy it into work_src so bindgen can find it.
        let generated_export = dst.join("include/libobsensor/h/Export.h");
        let target_export = work_src.join("include/libobsensor/h/Export.h");
        fs::copy(&generated_export, &target_export)
            .expect("Failed to copy generated Export.h into work_src");

        let cargo_manifest_dir = std::env::current_dir().unwrap();
        let target = std::env::var("TARGET").unwrap();
        codegen::generate_bindings(codegen::GenerateArgs {
            work_source_dir: work_src,
            sys_path: cargo_manifest_dir.join("src/sys"),
            target,
        });
    }
}

fn copy_dir_all(src: &Path, dst: &Path) -> std::io::Result<()> {
    fs::create_dir_all(dst)?;
    for entry in fs::read_dir(src)? {
        let entry = entry?;
        let ty = entry.file_type()?;
        let from = entry.path();
        let to = dst.join(entry.file_name());
        if ty.is_dir() {
            copy_dir_all(&from, &to)?;
        } else {
            fs::copy(&from, &to)?;
        }
    }
    Ok(())
}

fn dir_fingerprint(root: &Path) -> std::io::Result<String> {
    let mut entries = Vec::new();
    collect_entries(root, root, &mut entries)?;
    Ok(entries.join("\n"))
}

fn collect_entries(root: &Path, dir: &Path, out: &mut Vec<String>) -> std::io::Result<()> {
    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        let ty = entry.file_type()?;

        if ty.is_dir() {
            collect_entries(root, &path, out)?;
        } else {
            let rel = path.strip_prefix(root).unwrap();
            let meta = entry.metadata()?;
            let len = meta.len();
            let modified = meta
                .modified()?
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_secs();

            out.push(format!("{}:{}:{}", rel.display(), len, modified));
        }
    }
    out.sort();
    Ok(())
}
