/* automatically generated by rust-bindgen 0.72.0 */

#[doc = "@brief device time"]
#[repr(C, packed)]
#[derive(Debug, Copy, Clone)]
pub struct OBDeviceTime {
    #[doc = "< sdk->dev: timing time; dev->sdk: current time of device;"]
    pub time: u64,
    #[doc = "< sdk->dev: command round-trip time, the device sets the time to time+rtt/2 after receiving it; dev->sdk: reserved; unit: ms"]
    pub rtt: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of OBDeviceTime"][::std::mem::size_of::<OBDeviceTime>() - 16usize];
    ["Alignment of OBDeviceTime"][::std::mem::align_of::<OBDeviceTime>() - 1usize];
    ["Offset of field: OBDeviceTime::time"][::std::mem::offset_of!(OBDeviceTime, time) - 0usize];
    ["Offset of field: OBDeviceTime::rtt"][::std::mem::offset_of!(OBDeviceTime, rtt) - 8usize];
};
